#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: e36a856
#
Name     : R-R6
Version  : 2.6.0
Release  : 105
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/R6_2.6.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/R6_2.6.0.tar.gz
Summary  : Encapsulated Classes with Reference Semantics
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
built-in reference classes. Compared to reference classes, R6 classes
    are simpler and lighter-weight, and they are not built on S4 classes
    so they do not require the methods package. These classes allow public
    and private members, and they support inheritance, even when the
    classes are defined in different packages.

%prep
%setup -q -n R6
pushd ..
cp -a R6 buildavx2
popd
pushd ..
cp -a R6 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739467841

%install
export SOURCE_DATE_EPOCH=1739467841
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/R6/DESCRIPTION
/usr/lib64/R/library/R6/INDEX
/usr/lib64/R/library/R6/LICENSE
/usr/lib64/R/library/R6/Meta/Rd.rds
/usr/lib64/R/library/R6/Meta/features.rds
/usr/lib64/R/library/R6/Meta/hsearch.rds
/usr/lib64/R/library/R6/Meta/links.rds
/usr/lib64/R/library/R6/Meta/nsInfo.rds
/usr/lib64/R/library/R6/Meta/package.rds
/usr/lib64/R/library/R6/NAMESPACE
/usr/lib64/R/library/R6/NEWS.md
/usr/lib64/R/library/R6/R/R6
/usr/lib64/R/library/R6/R/R6.rdb
/usr/lib64/R/library/R6/R/R6.rdx
/usr/lib64/R/library/R6/help/AnIndex
/usr/lib64/R/library/R6/help/R6.rdb
/usr/lib64/R/library/R6/help/R6.rdx
/usr/lib64/R/library/R6/help/aliases.rds
/usr/lib64/R/library/R6/help/figures/logo.png
/usr/lib64/R/library/R6/help/figures/logo.svg
/usr/lib64/R/library/R6/help/paths.rds
/usr/lib64/R/library/R6/html/00Index.html
/usr/lib64/R/library/R6/html/R.css
/usr/lib64/R/library/R6/tests/manual/README
/usr/lib64/R/library/R6/tests/manual/encapsulation.R
/usr/lib64/R/library/R6/tests/manual/test-inheritance.R
/usr/lib64/R/library/R6/tests/testthat.R
/usr/lib64/R/library/R6/tests/testthat/helper.R
/usr/lib64/R/library/R6/tests/testthat/test-aslist.R
/usr/lib64/R/library/R6/tests/testthat/test-clone.R
/usr/lib64/R/library/R6/tests/testthat/test-cloning-inheritance.R
/usr/lib64/R/library/R6/tests/testthat/test-finalizer.R
/usr/lib64/R/library/R6/tests/testthat/test-is.R
/usr/lib64/R/library/R6/tests/testthat/test-nonportable-inheritance.R
/usr/lib64/R/library/R6/tests/testthat/test-nonportable.R
/usr/lib64/R/library/R6/tests/testthat/test-portable-inheritance.R
/usr/lib64/R/library/R6/tests/testthat/test-portable.R
/usr/lib64/R/library/R6/tests/testthat/test-s3-methods.R
/usr/lib64/R/library/R6/tests/testthat/test-set.R
